### ISSUE TITLE
Setup submodule to SteamVR repo

### ISSUE THREAD

**Issue by SimonDarksideJ** [XRTK/SteamVR#2]
# XRTK - Mixed Reality Toolkit Feature Request

## Is your feature request related to a problem? Please describe

Would be good to get this repo started with at least a submodule to the SteamVR repo in the runtime /plugins folder

**Comment by StephenHodgson** [comment]
Since @zite is planning on publishing this as a upm package I think it's best to consume it in that form instead of as a submodule in the long term, but short term I don't mind consuming it as this way as they do quick iterations.

**Comment by StephenHodgson** [comment]
Okay I take back my last comment. We'll want only a subset of the package so we don't collide with the Unity XR Subsystems. Submodule is best way to go.
